---
- hosts: azurevms
  vars_files:
     - "./vars.yml"
  gather_facts: no
  tasks:
  - name: Install IIS features
    win_feature:
      name: 
        - Web-Server
        - Web-Common-Http
        - Web-Mgmt-Service
      include_management_tools: yes
      include_sub_features: yes
      state: present
      
  - name: Enable IIS remote management
    win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\WebManagement\Server
      name: EnableRemoteManagement
      data: 1
      type: dword
      
  - name: Install WebDeploy
    win_package:
      path: https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi
      product_id: '{6773A61D-755B-4F74-95CC-97920E45E696}'
      arguments: ADDLOCAL=ALL
      state: present
 
  - name: Start and set management service to auto
    win_service:
      name: WMSvc
      start_mode: auto
      state: started

  - name: install .net 4.6.1 iis hosting module with no frameworks
    win_chocolatey:
      name: dotnet4.6.1
      state: present

  - name: install net 3.5 iis hosting module with no frameworks
    win_chocolatey:
      name: dotnet3.5
      state: present

  - name: Create logging directory
    win_file:
      path: c:\logs
      state: directory

  handlers:
    - name: restart IIS
      win_shell: '& {iisreset}'